src-ui/src/app/components/document-detail/document-detail.component.html, src-ui/src/app/components/document-detail/document-detail.component.ts
=> Add page number to document toolbar

docker/local/Dockerfile
This pull request closes #205.
=> Add missing libxslt-dev

docker/gunicorn.conf.py, docker/supervisord.conf
As per https://docs.gunicorn.org/en/stable/settings.html#bind
=> Gunicorn should bind to both ipv4 and ipv6

src-ui/src/app/components/manage/logs/logs.component.html
This PR closes #314 and fixes the color of log text in dark mode.
=> Fix log colors in dark mode

README.md, docs/setup.rst
Hi, as mentioned in #387 I have made some changes and added some text. At first only for the part of the introduction and Docker installation. Let me know if it fits or if it needs some changes.
=> Documentation changes

src-ui/src/app/components/dashboard/widgets/upload-file-widget/upload-file-widget.component.html, src-ui/src/app/components/dashboard/widgets/upload-file-widget/upload-file-widget.component.scss, src-ui/src/app/components/dashboard/widgets/upload-file-widget/upload-file-widget.component.ts, src-ui/src/app/services/consumer-status.service.ts, src-ui/src/styles.scss, src-ui/src/theme_dark.scss
This PR updates the style & functionality of consumer status notifications, see issue #415
https://user-images.githubusercontent.com/4887959/105920080-92378f00-5feb-11eb-8765-0892fb4a412b.mov
=> Updates to consumer status alerts

src-ui/src/app/components/app-frame/app-frame.component.html, src-ui/src/app/components/app-frame/app-frame.component.scss
This PR moves the "misc" section of the sidebar and renames it to "info" and updates its contents, see:
=> Updates to sidebar "Misc" section

ansible/README.md, ansible/defaults/main.yml, ansible/tasks/main.yml, docs/setup.rst
I missed a few `ng`s when introducing the variables.
=> Ansible - apply consistent name structure to vars

ansible/defaults/main.yml, ansible/tasks/main.yml
Include the newly added OCR clean and deskew parameters.
Also incorporate the contraints regarding OCR language mentioned in https://github.com/jonaswinkler/paperless-ng/issues/584#issuecomment-782830878.
=> Ansible - Update exposed configuration variables

src-ui/src/app/components/app-frame/app-frame.component.html, src-ui/src/app/components/app-frame/app-frame.component.scss, src-ui/src/app/components/app-frame/app-frame.component.ts, src-ui/src/theme_dark.scss
This PR closes #603 as discussed, it adds support for closing individual documents using an 'x' button which is only visible on hover in the sidebar.
Screenshot:
=> Allow closing individual documents from sidebar

src-ui/src/locale/messages.it.xlf
Minor change to Italian translation.
Manual PR since Transifex doesn't do it.
=> Update Italian Translation

src/paperless/checks.py
For some reason, os.access(directory, os.W_OK | os.X_OK) does not work correctly on NFS mounts.
After some research, found out that the only secure and portable way to check for write access, is to touch a file.
=> fix writable check for NFS mounts

docs/advanced_usage.rst
=> update advanced_usage.rst to remove wording regarding filename parsing

docs/scanners.rst
Some new scanners and a new Support column SMTP for Scanner which can directly send mails via SMTP. Also one iOS App to scan documents
=> Three new scanners, one iOS App and column for SMTP Support

docs/scanners.rst
Easy to use, open source, multi-page PDF support. Sharing PDF with paperless app works really nice
=> New android scanner app recommendation

src/paperless_tika/signals.py
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>
=> Add support for rtf

docs/administration.rst
This mechanism is already used for the installation process.
=> Use ansible-galaxy during updates

ansible/README.md
=> adjust ansible README to installation instructions

src/documents/management/commands/document_retagger.py, src/documents/signals/handlers.py, src/documents/tests/test_management_retagger.py
Add options in the document_retagger to be able to get some suggest of possible document classification errors.
=> Add suggest

docs/administration.rst
Give a hint to use "-t" flag for exec to use them in cron jobs
=> Info for The input device is not a TTY Errors

docs/setup.rst
Clarified exactly what to change to modify the default webserver port (issue #1273)
=> Updated docker instructions re webserver port
