Pipfile
src/documents/management/commands/document_consumer.py
src/documents/tests/test_management_consumer.py
src/paperless/settings.py

The names of sub directories in the consumer directory will be added as tags for the document to be consumed.
To enable this, set:
PAPERLESS_CONSUMER_RECURSIVE=1
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=1
Fixes #50
----
While this basically works, I had a bad time trying to test this. Debugging tests is a bit hard in general because of the async nature but in particular this always gives me table locking errors (for document_tags). While that might make sense, I also tried to not create tags in the document_consumer (just `Tags.objects.get()`) which seems to still lock the table.
I'm not an expert at Django ORM etc. et all, so maybe you have idea on how to work around this @jonaswinkler

Create tags from sub directories

---

docs/setup.rst

This was what happened when I tried to follow the steps:
```
$ docker-compose run --rm webserver document_index reindex 
Creating network "paperless_default" with the default driver
Pulling broker (redis:6.0)...
6.0: Pulling from library/redis
852e50cd189d: Pull complete
76190fa64fb8: Pull complete
9cbb1b61e01b: Pull complete
d048021f2aae: Pull complete
6f4b2af24926: Pull complete
1cf1d6922fba: Pull complete
Digest: sha256:5b98e32b58cdbf9f6b6f77072c4915d5ebec43912114031f37fa5fa25b032489
Status: Downloaded newer image for redis:6.0
Creating paperless_broker_1 ...
Creating paperless_broker_1 ... done
Operations to perform:
Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions
Running migrations:
No migrations to apply.
Unknown command: 'document_index'
Type …
```

Add missing step to migration guide

---

docker/local/Dockerfile

#95 
The qpdf header files are necessary for building pikepdf from source.
The latter is necessary on aarch64, because no public wheels for this package on the ARM platforms exist.
I can confirm that `docker-compose build` and paperless-ng run successfully with this change on 
`$ uname -a
Linux ubuntu 5.8.0-1008-raspi #11-Ubuntu SMP PREEMPT Thu Nov 12 15:49:32 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
`

Dockerfile: Add libqpdf-dev to build dependencies

---

src-ui/src/app/components/document-list/document-list.component.html
src-ui/src/app/components/filter-editor/filter-dropdown/filter-dropdown.component.html
src-ui/src/app/components/filter-editor/filter-dropdown/filter-dropdown.component.scss
src-ui/src/app/components/filter-editor/filter-dropdown/filter-dropdown.component.ts
src-ui/src/app/components/filter-editor/filter-editor.component.html

This is a new PR for #136
> @jonaswinkler I know mobile support in general is on the back burner but figured I'd at least improve the quick-filters I worked on (#111). Basically added breakpoints for smaller screens and then buttons become icons (except dates cause I couldn't think of good ones to differentiate them) on mobile screens to fit everything. Curious to see what you think! Screenshots below
> 
> Mobile:
> <img width="338" alt="Screen Shot 2020-12-14 at 4 19 31 PM" src="https://user-images.githubusercontent.com/4887959/102155477-78256100-3e30-11eb-81b5-6cfbea6ed150.png">
> 
> Medium displays:
> <img width="714" alt="Screen Shot 2020-12-14 at 4 20 06 PM" src="https://user-images.githubusercontent.com/4887959/102155480-79568e00-3e30-11eb-87cd-1b5c871c2281.png">
> 
> Large …

Mobile Improvements for "Quick Filters" (2)

---

src-ui/src/app/components/document-list/document-card-small/document-card-small.component.html
src-ui/src/app/components/document-list/document-list.component.html
src-ui/src/app/components/document-list/document-list.component.scss

Hi @jonaswinkler hope Im not annoying you with the PRs =) This very small one just tweaks the small card document list to keep it full width and the document cards evenly spaced, it just changes the bootstrap classes and I think looks a little cleaner. Screenshots below for reference!
Before:
After:
Before:
After:
Before:
After:
Before:
After:

Document list small card layout adjustments

---

src-ui/package-lock.json
src-ui/package.json
src-ui/src/app/app.module.ts
src-ui/src/app/components/common/input/select/select.component.html
src-ui/src/app/components/common/input/select/select.component.scss
src-ui/src/app/components/common/input/tags/tags.component.html
src-ui/src/app/components/common/input/tags/tags.component.scss
src-ui/src/app/components/common/input/tags/tags.component.ts
src-ui/src/app/components/document-detail/document-detail.component.html
src-ui/src/styles.scss

This closes #152 and includes searchable dropdowns for correspondents / document types / tags with [ng-select](https://www.npmjs.com/package/@ng-select/ng-select). The integration is customized to match paperless-ng including using `tag` components with custom colors, etc.

Searchable dropdowns on document details component

---

.travis.yml
Dockerfile

As discussed in https://github.com/jonaswinkler/paperless-ng/issues/151 I've been porting my old pull request from the-paperless-project over to this one.
It extends the travis-ci pipeline with three docker builds, one for each x86_64, aarch64 (arm64) and arm32v7 and then creates a multi-arch docker manifest, so it can be used seamlessly on all three platforms.
It makes use of travis-ci's new arm64-graviton2 build machine, so travis-ci.com (not .org) needs to be used. I was able to migrate my account within minutes, so I hope this is not a problem.
The following environment variables and secrets need to be defined in travis:
DOCKER_REPO (f.e. jonaswinkler/paperless-ng)
DOCKER_USERNAME (f.e. jonaswinkler)
DOCKER_PASSWORD (should not be your regular password, but rather a deployment key …

Automatic CI/CD multiarch docker builds

---

src-ui/src/app/components/document-list/bulk-editor/bulk-editor.component.html
src-ui/src/app/components/document-list/bulk-editor/bulk-editor.component.ts
src-ui/src/app/components/document-list/document-list.component.html
src-ui/src/app/components/document-list/document-list.component.ts

This PR addresses refactoring as discussed in https://github.com/jonaswinkler/paperless-ng/pull/162#issuecomment-750425915 , specifically `BulkEditor` now injects `DocumentListViewService` directly and performs operations without passing events to `DocumentList` component

Refactored bulk editor

---

src-ui/src/styles.scss

Again, hope Im not interrupting your "break" @jonaswinkler , obviously none of this stuff is urgent!
This PR fixes a small (but significant) annoyance on iOS Safari where `<input>` elements zoom the entire page when entered, for an app like Paperless-ng🎄 its pretty disruptive. This PR just selectively sets the font size to 16px on these elements _only on iOS Safari_ using CSS `@supports`. Small part of #24 
If youre curious theres more about this here: https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone . The alternative solution I have used in the past is to set `maximum-scale=1` to the `<meta name="viewport"` but that has [negative accessibility implications](http://a11yproject.com/posts/never-use-maximum-scale) and disables pinch-to-zoom on …

Avoid ios safari input zoom

---

.travis.yml

This pull request solves the question from this comment: https://github.com/jonaswinkler/paperless-ng/pull/178#issuecomment-750305475
> Let's also say I only want to build images for the branches `master`, `dev` and all tags that match `ng-*`, how would I do that? I don't necessarily need images for every commit, building and tagging `dev` is usually enough for testing before releases.
With this change, stages get defined and the docker specific stages are only executed if the branch or tag (for travis it's all the same) match this regex: `/^(master|dev|ng-.*)$/`
Hope we can get this in, also in the master, so I can start using the official images on my multi-arch k3s/k8s cluster :)

Travis multi-arch builds: only build and push docker containers on special branches and tags

---

src-ui/src/theme_dark.scss

As discussed in https://github.com/jonaswinkler/paperless-ng/pull/203#issuecomment-753370631 this PR:
- Increase contrast of text by increasing brightness of some dark-mode colors & changes to darker bg for tables
- Fixes inconsistent large card anchor color
- Fixes some button hover/active states

Visual fixes to dark mode elements

---

src-ui/src/app/components/common/edit-dialog/edit-dialog.component.ts
src-ui/src/app/components/manage/correspondent-list/correspondent-edit-dialog/correspondent-edit-dialog.component.html
src-ui/src/app/components/manage/document-type-list/document-type-edit-dialog/document-type-edit-dialog.component.html
src-ui/src/app/components/manage/tag-list/tag-edit-dialog/tag-edit-dialog.component.html

This PR fixes #164 as discussed in https://github.com/jonaswinkler/paperless-ng/issues/212#issuecomment-753410730 , it hides the pattern field if algorithm is set to "auto"
@jonaswinkler One thing I noticed is that its hard to tell what the default is, in the list of tags/correspondents under 'Matching' it just shows - and when you edit one of those the menu option is "Any", but is it actually ( / should it be)  "Auto"? LMK, obviously I can sort it out if its just kind of a UI quirk
Edit: I see in Django admin default is "Any", so perhaps Angular UI should show same?

Hide matching pattern if algorithm is auto

---

src-ui/src/theme_dark.scss

This PR closes #276 as discussed therein, it addresses a few dark mode inconsistencies.

Fix more dark mode inconsistencies

---

src-ui/src/app/components/app-frame/app-frame.component.scss
src-ui/src/app/components/dashboard/widgets/saved-view-widget/saved-view-widget.component.scss
src-ui/src/theme_dark.scss

Sorry for the 1 line PR but my OCD cant leave this alone. Turns out Safari has a bug that requires css transitions on `flex` property to be 'all' (took me a while to figure that out), see https://codepen.io/chriscoyier/pen/dyXqpjJ
EDIT: 
Now includes
- Fixes search field animation in Safari 😀
- Fixes dashboard widget table layout overflow issue on mobile
- Fixes ng-select highlighting with keyboard navigation in dark theme
Awesome work on the last release, amazing how much this project has added as of late!

Miscellaneous CSS fixes

---

src-ui/src/app/components/document-list/document-card-large/document-card-large.component.html

YABSDMCB (yet another browser-specific dark mode CSS bug). This fixes buttons on large cards (actually its the HTML not CSS, but yea).

Fix dark mode button display on large cards in certain browsers

---

docs/setup.rst

In theory, this package is optional since not everybody wants to compile translations.
Without other changes to step 5. (i.e. making it explicit that `python3 manage.py compilemessages` is not mandatory), not installing `gettext` results in an error when blindly copy-pasting the steps.

Add gettext to  Bare Metal Route dependencies

---

src-ui/src/app/components/document-list/document-card-large/document-card-large.component.html
src-ui/src/app/components/document-list/document-card-large/document-card-large.component.scss

Just taking care of these randomly as I come across them, part of #24 , this PR corrects some issues with large cards (which are also used for search results). Screenshots below.
Before:
After:
Before:
After:

Fixes for large cards / search results on mobile

---

.github/workflows/ansible.yml
.travis.yml
ansible/README.md
ansible/defaults/main.yml
ansible/meta/main.yml
ansible/molecule/default/converge.yml
ansible/molecule/default/molecule.yml
ansible/molecule/default/verify.yml
ansible/tasks/main.yml

I've really grown fond of the project.
After installing it manually twice, it is now time to automate the process (docker is not an option in my case).
This is largely based on the official [bare-metal route](https://paperless-ng.readthedocs.io/en/latest/setup.html#bare-metal-route).
Caveats
- Currently only Debian 10 buster is supported
- Intended to be installed in _dirty_ enviroments (with other users/services)
- dedicated user for paperless-ng
- .venv
- dropped permissions of the services
- Database deployment is considered out-of-scope and deferred to the user
- Provides basic upgrade support between releases
- `jbig2enc` is pulled from https://notesalexp.org/ (owned by @AlexanderP)
ToDo

Provide an ansible role for deployment and configuration

---

ansible/defaults/main.yml
ansible/tasks/main.yml

This incorporates the following changes from `0.9.14`:
- remove `collectstatic` and `compilemessages` steps as the required files ship in the release archives
- `PAPERLESS_DBSSLMODE`
This change also mirros the structure of the configuration [doc](https://paperless-ng.readthedocs.io/en/ng-0.9.14/configuration.html). More options have been made configurable.

Ansible - Update to 0.9.14

---

docs/configuration.rst

 Fix ENV var name for user args in documentation

---

ansible/README.md
docs/setup.rst

Ansible - Provide documentation

---

src-ui/src/app/components/document-list/document-card-large/document-card-large.component.html
src-ui/src/app/components/document-list/document-card-large/document-card-large.component.ts
src-ui/src/app/components/document-list/document-card-small/document-card-small.component.html
src-ui/src/app/components/document-list/document-card-small/document-card-small.component.ts
src-ui/src/app/components/document-list/document-list.component.html
src-ui/src/app/components/document-list/document-list.component.scss
src-ui/src/app/components/document-list/document-list.component.ts
src-ui/src/app/services/document-list-view.service.ts

This PR closes #347 and adds support for "shift-click" to select multiple documents. A couple notes @jonaswinkler because I know you run a tight ship:
1. I moved all selection functions out of the cards partly to be able to detect shift key when clicking (e.g. from `MouseEvent`) but also they seemed redundant since cards/`tr`s have an input to determine selection like `[selected]="list.isSelected(d)"`
2. I also updated cards & `tr`s to allow clicking anywhere on the item (e.g. entire card or anywhere in the `tr`. This feels like it makes more sense UI-wise (also since the checkbox shows on hovering the entire card it is kind a tiny 'bug' that you could hover but not click) but let me know if you think otherwise.
3. Selecting mimics what I saw in other systems. For example if you reverse …

Allow shift-select in documents list

---

src-ui/src/app/components/common/edit-dialog/edit-dialog.component.ts
src-ui/src/app/components/document-list/save-view-config-dialog/save-view-config-dialog.component.html
src-ui/src/app/components/document-list/save-view-config-dialog/save-view-config-dialog.component.ts
src-ui/src/app/components/manage/correspondent-list/correspondent-edit-dialog/correspondent-edit-dialog.component.html
src-ui/src/app/components/manage/document-type-list/document-type-edit-dialog/document-type-edit-dialog.component.html
src-ui/src/app/components/manage/tag-list/tag-edit-dialog/tag-edit-dialog.component.html

This PR closes #350 as discussed. @jonaswinkler the solution might seem odd but I have found that trying to force browser focus _to_ something is much less reliable than preventing focus on the wrong thing =) So the solution (which works in Chrome/Saf/FF in my testing) is to disable the close button until modal has started opening and browser will have already given focus to the input. I also implemented this for the save view modal.

Prevent close button in modal dialogs 'stealing' focus

---

.github/workflows/ansible.yml
ansible/molecule/default/converge.yml
ansible/tasks/main.yml

Solves problems of non-explicit refspecs.

Ansible - Switch CI target to sha instead of ref

---

.github/workflows/ansible.yml
ansible/molecule/default/converge.yml

Do not require molecule teardown for success.
CI failures should not be caused by intermittently failing docker
communication furing test teardown.

Ansible - Improve CI stability

---

.github/workflows/ansible.yml
ansible/molecule/default/converge.yml

Follow-up to #630.
The check for the target git sha does not work in the molecule step.
Instead expose the sha through an env variable in GitHub actions.
This addresses the issue of re-running GitHub actions workflows as explained in https://github.com/jonaswinkler/paperless-ng/pull/602#issuecomment-785261225.

Ansible - Fix GitHub actions

---

scripts/start_services.sh

Postgres needs a superuser password when running with an un-initialized database.
After running the start_services.sh script, I noticed that the Postgres container wasn't running. 
Upon inspecting the logs of the container, I could see the following message:
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
connections without a password. This is *not* recommended.
See PostgreSQL documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
```
This change just adds a password so that the DB can run.

Postgres won't run without a password.

---

install-paperless-ng.sh

Refers to: #686 
The install script does not check if a user has the necessary permissions to run Docker (-Compose). The documentation also does not describe further how to give a non-root user permissions to Docker. At least, I did not see such a description at first glance. Therefore, I implemented a check that verifies if a user has the required Docker permissions. 
For this purpose, when starting the script, it tries to call `docker status --no-stream`.  
If a user has the required permissions, it exits with status 0, otherwise 1.
If a user has no Docker permissions, the following message is displayed and the script is stopped for 3 seconds:
```bash
noperm@test:~$ ./install-paperless-ng.sh
WARN: It look like the current user does not have Docker permissions.
WARN: Use 'sudo usermod …
```

Installation Script: Check for Docker permissions on startup

---

README.md
docs/changelog.rst
src-ui/messages.xlf
src-ui/src/app/components/document-list/filter-editor/filter-editor.component.ts
src/documents/tests/test_api.py

Implements #664 
---
Basically, the PR adds a "Filter by: ASN" Option, through which you can search documents directly by the ASN:

Implemented 'Filter by: ASN'

---

src-ui/src/app/components/document-list/document-card-large/document-card-large.component.html
src-ui/src/app/components/document-list/document-card-large/document-card-large.component.scss
src-ui/src/app/components/document-list/document-card-large/document-card-large.component.ts
src-ui/src/app/components/document-list/document-card-small/document-card-small.component.html
src-ui/src/app/components/document-list/document-card-small/document-card-small.component.scss
src-ui/src/app/components/document-list/document-card-small/document-card-small.component.ts
src-ui/src/app/components/document-list/document-list.component.html
src-ui/src/theme_dark.scss

This PR addresses #423 and #439 and adds / organizes info on cards (ASN, doc type). Screenshots below. Highlights:
- Document type (if set) is displayed without tooltip
- Doc type is clickable for quick filtering
- Date created & ASN (if set) are also shown in similar organized manner
- Overall height of small cards only varies +/- 10% depending on the number of items shown, so still works well on narrow (mobile) screen sizes
- Larger action buttons on small cards
- Nice & neat =)
Of course, please let me know if I missed any issues

Additional / organized card info

---

src-ui/src/app/components/document-list/document-card-large/document-card-large.component.scss
src-ui/src/app/components/document-list/document-card-small/document-card-small.component.scss

Not sure why I wasnt seeing this before but in Safari (not in Chrome at least on my machine) the icons are sometimes cut off. Solution is just a tiny bit of padding with css. Screenshot attached for reference.

Fix additional card info icons sometimes cut off in certain browsers

---

src-ui/src/app/components/manage/logs/logs.component.html
src-ui/src/app/components/manage/logs/logs.component.scss
src-ui/src/app/components/manage/logs/logs.component.ts

This PR closes #774 and #775 , it:
- Fixes css that caused an extra scrollbar on the log container
- ~~Reverses the order of log output (newest first)~~
- Automatically scrolls logs to the bottom

Fix extra scrollbar on log container, auto scroll logs to bottom

---

src-ui/src/app/components/common/input/select/select.component.html
src-ui/src/app/components/common/input/select/select.component.ts
src-ui/src/app/components/common/input/tags/tags.component.html
src-ui/src/app/components/common/input/tags/tags.component.ts
src-ui/src/app/components/document-detail/document-detail.component.html
src-ui/src/app/components/document-detail/document-detail.component.ts
src-ui/src/styles.scss

This PR addresses #817 , it implements passing the current search term to a "Create New" dialog for tags, document types & correspondents on the document edit page.
~~@jonaswinkler Ha, as usual, this was slightly more complicated than I thought but I think this is a clean solution. Because the native `ng-select` component immediately clears search terms on `blur`, the value needs to be stored with `search` events. Then on blur a timeout is set for 3 seconds to allow passing to the dialog if that is the next action, otherwise its cleared. The stored term is also cleared appropriately with pressing clear button, re-entering the field and when the new dialog event fires. Basically this is to prevent the search term hanging around long after a user actually interacted with the field. Let me …

Support passing current term from tag / document type / correspondent search field to 'create new' dialog

---

src-ui/src/app/components/document-list/document-card-large/document-card-large.component.html

This miniscule PR fixes a minor layout bug after merging the search UI (which, btw, is totally awesome). Screenshot below.
One extra note: I noticed you swapped the L-to-R order of the search score & info icons, I kinda think it makes more sense to have score on the left so that the icons are always in the same spot, bottom right. If you agree I can swap that too but obviously NBD if not.

Fix alignment of card info on large cards

---

src-ui/src/app/components/document-list/document-list.component.html
src-ui/src/app/components/document-list/document-list.component.scss
src-ui/src/theme.scss
src-ui/src/theme_dark.scss

This PR addresses issue #907 and makes the filter / bulk editors "sticky" to the top of the window on scroll. See video below. A couple notes:
- This is tested in Chrome / Safari / FF / Opera, appreciate any other testing
- Uses css `position: sticky` which is pretty well supported in recent browsers, see https://caniuse.com/css-sticky
https://user-images.githubusercontent.com/4887959/114746879-105f2400-9d05-11eb-84e5-72980c3ad8c7.mov

"Sticky" filter editor and bulk editor

---

docker/compose/docker-compose.portainer.yml

Portainer is often used to manage docker-compose stacks, I personally use it in an openmediavault installation. The gui is a bit less flexible when it comes to mutliple configuration files. This PR adds a docker-compose file that can be used in this case. The env variables are configured within the yml file and an alternative instruction for superuser creation via gui is added.
Additionally, the default exposed port is set to 8010 as port 8000 is reserved by portainer itself.

add single compose file for usage in portainer environments

---

Dockerfile
docker/docker-entrypoint.sh
docker/management_script.sh

While investigating #879 I came across gosu which is used by postgres to run their process as a different user in the container after doing some setup as root. We might consider adapting it to avoid future problems with sudo.

Use gosu as it is less complicated than sudo

---

src-ui/src/app/components/document-detail/document-detail.component.html

@jonaswinkler sorry for the 1 line PR but figured I would do this so you dont have to think about it. 
This PR removes the `type` attribute of the PDF `object` tag which causes Safari macOS to crash when viewing PDFs, see https://github.com/jonaswinkler/paperless-ng/issues/65#issuecomment-778433328
One other thing Jonas, do you think we should change the "use native PDF" setting to default to `true` now? I think so, LMK I can add it here

Remove PDF type attribute to fix macOS Safari native PDF viewer crashing

---

docs/setup.rst

use ansible-galaxy to fetch the ansible scripts to have a role called paperless-ng instead of ansible

Use ansible-galaxy for ansible setup

---

docs/setup.rst

Since the jbig2enc dependency is pulled from a repository that only provides i386 and amd64 packages, the installation will fail on arm hosts.

Mention lacking support for ARM in ansible setup

---

src-ui/src/print.scss
src-ui/src/styles.scss

Allow printing of the document list in a clean way
* Hide sidebar, filter
* Use full width
See also https://github.com/jonaswinkler/paperless-ng/discussions/126
Preview of the print out
How to generate a TOC
* Filter by the ASNs in you want to generate a ToC for using advanced search - `asn:[1 to 100]`
* Use the print function of your webbrowser
Known issues: 
* You still have to print each page manually, if the document spans more then one page
* Sorting needs to be fixed: https://github.com/jonaswinkler/paperless-ng/issues/975

Add print css for document list

---

src/documents/management/commands/document_archiver.py
src/documents/management/commands/document_exporter.py
src/documents/management/commands/document_importer.py
src/documents/management/commands/document_index.py
src/documents/management/commands/document_renamer.py
src/documents/management/commands/document_retagger.py
src/documents/management/commands/document_sanity_checker.py
src/documents/management/commands/document_thumbnails.py
src/documents/sanity_checker.py
src/documents/tasks.py

The progress bar is relay not useful when we call the commands from a cron job.

Add --no-progress-bar option to commands

---

src/paperless_mail/mail.py

Some mail servers (mail.ru) do not support search criteria for the maximum age. By setting the maximum age to 0, it is possible to bypass the search criteria. This PR solves that problem.

Solving issue with search criteria 'maximum age' for some mail server

---

docs/setup.rst

The installation for docker is currently three separate commands, but it can be a single command if the user simply pipes to the sh interpreter directly. I know there are some who object to piping to sh from a URL, but the current method has no security benefit over piping directly to sh.

Simplify installation command

---

docs/configuration.rst

Documentation describing how to change the expected date format while parsing documents.

Document specification of the expected creation date order

---

src-ui/angular.json
src-ui/src/app/app.module.ts
src-ui/src/app/services/settings.service.ts
src/paperless/settings.py

Depends on #1153 to be merged as well.
I added the new language at the bottom of the different lists as they were not alphabetical.
I think it makes more sense for the languages to be ordered alphabetically by ISO code. Let me know if that would be ok for you, then I could do that in a second commit (or a separate PR, whatever you prefer).

Added support for Luxembourgish (lb_LU) as an interface language

---

docs/scanners.rst

Hi everyone,
I've really been enjoying paperless-ng and have never had any problems with it. I now want to share the scanner I've been using.
The scanner in question is the [Doxie Q / Q2](https://www.getdoxie.com/product/doxie-q), which is pretty open with HTTP-POST-Support to a custom endpoint and a local API exposed over WiFi. (See [Doxie API-Documentation](https://help.getdoxie.com/doxieq/wifi/api/)) I've been pointing the POST-endpoint directly at paperless-ng, so my scanned documents will arrive in paperless as soon as they're done scanning.
If you have any questions feel free to ask me!
Have a nice day,
Kevin

Add Doxie Q to scanners.rst

---

docs/configuration.rst

Due to tesseract naming scheme, packages use '-' but the internal OCR uses '_' . This is to clarify in the documentation that this is the case for new users.

update configuration docs for languages

---

docker/compose/docker-compose.postgres-tika.yml
docker/compose/docker-compose.sqlite-tika.yml
docs/configuration.rst
docs/troubleshooting.rst
scripts/start_services.sh
src/paperless_tika/parsers.py

This commit adapts to the latest breaking changes from Gotenberg 7. Changes as follows:
* Change from https://hub.docker.com/r/thecodingmachine/gotenberg to new official https://hub.docker.com/r/gotenberg/gotenberg/ docker repository
* Freeze the usage of the Gotenberg server to v7.x. Doing this prevents further breaking changes leaking in our code base
* Change endpoint from `/convert/office` to `/forms/libreoffice/convert` ([documentation](https://gotenberg.dev/docs/modules/libreoffice#convert))
* Adapt environment variables ([documentation](https://github.com/gotenberg/gotenberg/blame/cc1ad1668877dd8b1ef32624aae49094d58cd183/Makefile))
* From `DISABLE_GOOGLE_CHROME` to `CHROMIUM_DISABLE_ROUTES`
* From `DEFAULT_WAIT_TIMEOUT` to `API_PROCESS_TIMEOUT`
Let me know if you need more …

fix(tika): adapt to Gotenberg 7 API

---

ansible/tasks/main.yml

This fixes the ansible role for installing paperless-ng where the config
item PAPERLESS_TIKA_GOTENBERG_ENDPOINT derived from the wrong ansible
variable "paperlessng_tika_endpoint".  This patch corrects that to
"paperlessng_tika_gotenberg_endpoint".

Fix PAPERLESS_TIKA_GOTENBERG_ENDPOINT in a/t/main.yml

---

docs/configuration.rst
src/paperless/settings.py

Currently with external SSO (`PAPERLESS_ENABLE_HTTP_REMOTE_USER`), clicking "Logout" will tell the user that it was successful when in reality they are of course still logged in.
The new setting `PAPERLESS_LOGOUT_REDIRECT_URL` allows the user to be redirected to the real logout page (of the SSO app). The patch is almost trivial, because [the functionality already exists in Django](https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-LOGOUT_REDIRECT_URL).

Add PAPERLESS_LOGOUT_REDIRECT_URL

---

src-ui/src/app/components/document-list/document-list.component.html

This PR addresses feature request #1260 and adds a loading indicator (spinner + text) to the documents list while a filter / search is being processed. See video below.
@jonaswinkler you still out there buddy?
https://user-images.githubusercontent.com/4887959/132621027-b31da84e-3603-48db-8e2b-2f98fd94edb6.mov

Add loading indicator when document list reloading

---

README.md

Fixed a reference to a docker/hub folder which should have been docker/compose.

Incorrect path to docker-compose files
